-- Начальная схема gate-service.
-- Типы подобраны под то, что ожидает Hibernate для PostgreSQL, потому что приложение
-- стартует с ddl-auto=validate: расхождение схемы и сущностей должно ловиться на старте,
-- а не всплывать первым же запросом в проде.

CREATE TABLE users (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        varchar(64)  NOT NULL,
    password_hash   varchar(255) NOT NULL,
    role            varchar(16)  NOT NULL,
    blocked         boolean      NOT NULL DEFAULT false,
    approved        boolean      NOT NULL DEFAULT true,
    created_at      timestamp(6) with time zone NOT NULL,
    last_login_at   timestamp(6) with time zone,
    failed_attempts integer      NOT NULL DEFAULT 0,
    locked_until    timestamp(6) with time zone
);

-- Логины сравниваются без учёта регистра, поэтому уникальность тоже по нижнему регистру:
-- обычный UNIQUE(username) пропустил бы пару Admin/admin.
CREATE UNIQUE INDEX uq_users_username_lower ON users (lower(username));

CREATE TABLE services (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(64)  NOT NULL,
    display_name varchar(128) NOT NULL,
    description  varchar(512),
    scheme       varchar(8)   NOT NULL DEFAULT 'http',
    host         varchar(255) NOT NULL,
    port         integer      NOT NULL,
    public_url   varchar(512),
    enabled      boolean      NOT NULL DEFAULT true,
    icon         varchar(8),
    sort_order   integer      NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX uq_services_name_lower ON services (lower(name));

CREATE TABLE user_service_access (
    user_id    bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    service_id bigint NOT NULL REFERENCES services (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, service_id)
);

CREATE INDEX idx_access_service ON user_service_access (service_id);

CREATE TABLE activity_log (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at  timestamp(6) with time zone NOT NULL,
    username     varchar(64),
    user_id      bigint,
    type         varchar(32)  NOT NULL,
    category     varchar(16)  NOT NULL,
    success      boolean      NOT NULL DEFAULT true,
    service_name varchar(64),
    ip           varchar(64),
    user_agent   varchar(256),
    detail       varchar(512)
);

-- user_id намеренно без внешнего ключа: журнал должен пережить удаление пользователя
-- и фиксировать попытки входа под логином, которого никогда не существовало.
CREATE INDEX idx_activity_at       ON activity_log (occurred_at DESC);
CREATE INDEX idx_activity_username ON activity_log (username);
CREATE INDEX idx_activity_type     ON activity_log (type);

CREATE TABLE gate_settings (
    setting_key   varchar(64) PRIMARY KEY,
    setting_value varchar(1024)
);
